Make the existing tests run using scripts/test
PublicMapping/districtbuilder-classic pull request #489
Opened 2018-01-15 20:23 UTC by shreshthkhilani

## Overview

This PR makes the existing `redistricting/tests.py` run. It fixes enough Django and database problems to make the tests run, but doesn't fix the errors in the tests themselves. 

This also calls changes the STRTA `script/test` to run these tests to make it easier to set up CI. 

### Checklist

- [ ] PR has a name that won't get you publicly shamed for vagueness

### Notes

The test db that Django stands up already has a row in the `django_site` table with "example.com" as the domain. Since this was causing a collision with the fixtures file, the fixtures file domain was changed to "examples.com". 

 A Django 1.8 issue made hardcoding the language necessary for testing. Refer to [this issue](https://github.com/django-parler/django-parler/issues/90).

## Testing Instructions

 * `vagrant ssh`
 * `./scripts/test`
 * Confirm that the tests run (not that they pass; they don't).

2018-01-15 21:14 UTC, jisantuc requested changes
One thing that would be helpful would be if the test classes split into separate files in a `tests/` directory, which I think is more like "best practice" at this point. If nothing else it will make our lives a lot better when we start working on fixing the failing tests.

2018-01-16 17:28 UTC, shreshthkhilani commented
@jisantuc broken up into multiples files in the /tests dir

2018-01-16 18:06 UTC, jisantuc requested changes
Omg so much more readable

Can you move the `tests/` dir into the redistricting app (since they're tests of the `redistricting` app's models)? Other than that, just a little bit of cleanup. This is great.

2018-01-16 18:06 UTC, jisantuc commented on django/publicmapping/tests/test_config.py
> +# from redistricting.tasks import *
Remove these stray commented imports

2018-01-16 18:06 UTC, jisantuc commented on django/publicmapping/tests/test_multi_member.py
> +# from redistricting.reportcalculators import *
Remove

2018-01-16 18:06 UTC, jisantuc commented on django/publicmapping/tests/test_plan.py
> +from redistricting.models import *
Probably open a story in PT for removing all remaining `import *`s

2018-01-16 18:06 UTC, jisantuc commented on django/publicmapping/tests/test_plan.py
> +        # Plan looks like this now:
I had no idea we had ascii art in this project, I love this.

2018-01-16 19:28 UTC, shreshthkhilani commented
Story created, directory moved, and comments removed. Thanks!

2018-01-16 21:13 UTC, jisantuc approved these changes
I'd say "pending Travis," but we both know how well that's going to go. :+1:

2018-01-16 21:17 UTC, merged